const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.JavaScriptInEvents.FolhaFase1_Event1_Act1,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{TelaInicial: 0},
	{NomeJogo: 0},
	{Jogar: 0},
	{Mouse: 0},
	{entrouPortal: 0},
	{BoundTo: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Jogador: 0},
	{Teclado: 0},
	{Vazio: 0},
	{Sólido: 0},
	{Chao1: 0},
	{Chao2: 0},
	{Chao3: 0},
	{cristais: 0},
	{Cristal: 0},
	{Âncora: 0},
	{Cristais: 0},
	{Sprite2: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{BGFase2: 0},
	{BGFase1: 0},
	{Sprite4: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite5: 0}
];

self.InstanceType = {
	TelaInicial: class extends self.ITiledBackgroundInstance {},
	NomeJogo: class extends self.ISpriteInstance {},
	Jogar: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Vazio: class extends self.ISpriteInstance {},
	Chao1: class extends self.ISpriteInstance {},
	Chao2: class extends self.ISpriteInstance {},
	Chao3: class extends self.ISpriteInstance {},
	Cristal: class extends self.ISpriteInstance {},
	Cristais: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BGFase2: class extends self.ITiledBackgroundInstance {},
	BGFase1: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}