const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.FolhaFase1_Event2_Act3,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.JavaScriptInEvents.FolhaFase2_Event8_Act3,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.AddVar,
		C3.JavaScriptInEvents.Eventosplayer_Event11_Act1,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{TelaInicial: 0},
	{Mouse: 0},
	{entrouPortal: 0},
	{BoundTo: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Jogador: 0},
	{Teclado: 0},
	{Abismo: 0},
	{Sólido: 0},
	{Chao1: 0},
	{Chao2: 0},
	{Chao3: 0},
	{cristais: 0},
	{Cristal: 0},
	{Âncora: 0},
	{Cristais: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{BGFase2: 0},
	{BGFase1: 0},
	{ChaoFase2: 0},
	{Projétil: 0},
	{Ataque: 0},
	{direcao: 0},
	{Inimigo: 0},
	{Virar: 0},
	{Sprite: 0},
	{vidas: 0},
	{BGGamerOver: 0},
	{TentarNovamente: 0},
	{Sair: 0},
	{Áudio: 0},
	{Senóide: 0},
	{Sprite4: 0},
	{BGJGConcluido: 0},
	{SairJC: 0},
	{Sprite5: 0},
	{Jogar: 0}
];

self.InstanceType = {
	TelaInicial: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Abismo: class extends self.ISpriteInstance {},
	Chao1: class extends self.ISpriteInstance {},
	Chao2: class extends self.ISpriteInstance {},
	Chao3: class extends self.ISpriteInstance {},
	Cristal: class extends self.ISpriteInstance {},
	Cristais: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BGFase2: class extends self.ITiledBackgroundInstance {},
	BGFase1: class extends self.ITiledBackgroundInstance {},
	ChaoFase2: class extends self.ISpriteInstance {},
	Ataque: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Virar: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	vidas: class extends self.ITextInstance {},
	BGGamerOver: class extends self.ISpriteInstance {},
	TentarNovamente: class extends self.ISpriteInstance {},
	Sair: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	BGJGConcluido: class extends self.ISpriteInstance {},
	SairJC: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Jogar: class extends self.ISpriteInstance {}
}